### ISSUE TITLE
Update docs with (link) howto for remote api setup

### ISSUE THREAD

**Issue by davesann** [palletops/lein-uberimage#12]
remote api is not always enabled by default. This results in a connection refused error.

For ubuntu I found this link helpful:

http://www.virtuallyghetto.com/2014/07/quick-tip-how-to-enable-docker-remote-api.html

(note: change "service docker restart" to "service docker.io restart")

**Comment by hugoduncan** [comment]
Adding this next to the existing links to the docker and coreos docs in the readme makes sense,
