### ISSUE TITLE
baseimage should be specified in project.clj for build consistency

### ISSUE THREAD

**Issue by davesann** [palletops/lein-uberimage#13]
Rather than using a cmd line option the base image might be better specified in the project file. This allows more consistency of build.

**Comment by hugoduncan** [comment]
Definitely a good idea to be able to specify this in `project.clj`.  I would keep the command line option though.

**Comment by hugoduncan** [comment]
The `:base-image` key should already work for this actually.

**Comment by davesann** [comment]
I thought that. But I tried a few combinations and it did not work. After staring at the code for a while, I came to the conclusion that it is most likely overwritten by the default being set by parse-opts. I didn't dig further to confirm that.

Agree. keep cmd line too.

**Comment by hugoduncan** [comment]
Your code staring yielded more correct results than mine - I think you are correct.
