### ISSUE TITLE
Support %s in :target-path

### ISSUE THREAD

**Issue by hugoduncan** [palletops/lein-uberimage#3]
When `project.clj` contains a profile specific `:target-path` (using `%s`), the plugin fails to find the generated jar file, and fails with the message:

```
Jar file does not exist
```

**Comment by vijaykiran** [comment]
As an ugly hack I used the `uberjar`s return value as the filename and it seems to work fine with
 `:target-path  "target/%s"`

``` clojure
(let [{:keys [piped-input-stream piped-output-stream tar-output-stream]}
          (tar-output-stream)
          jarfile (try
                    (uberjar project)
                    (catch Exception e
                      (when main/*debug*
                        (.printStackTrace e))
                      (throw
                       (ex-info "Uberimage aborting because uberjar failed:" {} e))))]
```

**Comment by hugoduncan** [comment]
@vijaykiran if you could do a pull-request for that, I would be happy to merge it.
